/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f401xx.h"
#include "gpio.h"

void delay(void)
{
    for(uint32_t i = 0; i < 500000; i++);
}
int main(void)
{
	GPIO_Handle_t GpioLed1, GpioLed2, GpioButton1;

	// Cấu hình PA5
	GpioLed1.pGPIOx = GPIOA;
	GpioLed1.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
	GpioLed1.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioLed1.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GpioLed1.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioLed1.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_NO_PUPD;
	GPIO_Init(&GpioLed1);

	// Cấu hình PA6
	GpioLed2.pGPIOx = GPIOA;
	GpioLed2.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_6;
	GpioLed2.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioLed2.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GpioLed2.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioLed2.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_NO_PUPD;
	GPIO_Init(&GpioLed2);

    GpioButton1.pGPIOx = GPIOA;
    GpioButton1.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_8;
    GpioButton1.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	//GpioLed2.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	//GpioLed2.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    GpioButton1.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;
	GPIO_Init(&GpioButton1);

	while(1){

	    if(GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_8) == 0) {  // Nếu nút được nhấn
	        GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_5);
	        GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_6);
	        delay();
	    }


	}

}
