/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <string.h>
#include "stm32f401xx.h"
#include "gpio.h"
#include "spi.h"
#define BTN_PRESSED 0

void delay(void)
{
    for(uint32_t i = 0; i < 500000; i++);
}

/*
 * Alternate functionality
 *
 * PB15 --> SPI2_MOSI
 * PB14 --> SPI2_MISO
 * PB13 --> SPI2_SLCK
 * PB12 --> SPI2_NSS
 * ALT function mode: AF5
 */

void SPI2_GPIOInits(void)
{
    GPIO_Handle_t SPIPins;

    SPIPins.pGPIOx = GPIOB;
    SPIPins.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
    SPIPins.GPIO_PinConfig.GPIO_PinAltFunMode = 5;
    SPIPins.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    SPIPins.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_NO_PUPD;
    SPIPins.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;

    /* SCLK Init */
    SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
    GPIO_Init(&SPIPins);

    /* MOSI Init */
    SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
    GPIO_Init(&SPIPins);

    /* MISO Init */
    SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
    GPIO_Init(&SPIPins);

    /* NSS Init (Only if using hardware NSS) */
     SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
     GPIO_Init(&SPIPins);
}

void SPI2_Inits()
{
    SPI_Handle_t SPIHandle;

    SPIHandle.pSPIx = SPI2;
    SPIHandle.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FD;
    SPIHandle.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;
    SPIHandle.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV2; // 8MHz
    SPIHandle.SPIConfig.SPI_DFF = SPI_DFF_8BITS;
    SPIHandle.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;
    SPIHandle.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;
    SPIHandle.SPIConfig.SPI_SSM = SPI_SSM_DI;  // Use Software NSS

    SPI_Init(&SPIHandle);

    SPI_SSOEConfig(SPI2, ENABLE);
}

void debugLED_Init(void) {
    GPIO_Handle_t LED;
    LED.pGPIOx = GPIOA;  // Use PA5 (on-board LED for STM32F401)
    LED.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
    LED.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
    LED.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    LED.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    LED.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_NO_PUPD;
    GPIO_Init(&LED);
}

void debugLED_Toggle(void) {
    GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_5);
}
int main(void)
{
    char user_data[] = "Hello World!";

    /* Initialize GPIO pins to behave as SPI2 pins */
    SPI2_GPIOInits();

    /* Initialize SPI2 peripheral parameters */
    SPI2_Inits();

    /* Enable SPI */
    SPI_PeripheralControl(SPI2, ENABLE);

    while (1)
    {
        // Manually set NSS LOW before sending data
        GPIO_WriteToOutputPin(GPIOB, GPIO_PIN_NO_12, SET);

        //while (SPI_GetFlagStatus(SPI2, SPI_SR_BSY)); // Ensure SPI is not busy
        SPI_SendData(SPI2, (uint8_t*)user_data, strlen(user_data));

        //while (SPI_GetFlagStatus(SPI2, SPI_SR_BSY)); // Confirm SPI finished

        // Manually set NSS HIGH after sending data
        GPIO_WriteToOutputPin(GPIOB, GPIO_PIN_NO_12, RESET);

        delay();
    }

    return 0;
}


